name: calendario_deportivos_app
description: Una app para crear calendarios de encuentros deportivos con soporte offline.
publish_to: 'none' # Esto evita que se publique en pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 📦 Paquetes principales
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  uuid: ^4.1.0
  connectivity_plus: ^5.0.1
  csv: ^5.1.1
  pdf: ^3.10.4
  share_plus: ^7.2.1
  open_file: ^3.3.2
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
